shell_packages_utility:
  - bat
  - curl
  - eza
  - fd-find
  - fzf
  - fzy
  - "{{ ansible_facts['distribution_version'] is version('13', '>=') | ternary('git-delta', False) }}"
  - jq
  - keychain
  - "{{ ansible_facts['distribution_version'] is version('12', '>=') | ternary('lf', False) }}"
  - parallel
  - plocate
  - ripgrep
  - sed
  - tree

shell_packages_zsh:
  - zsh
  - zsh-doc

shell_packages_lua:
  - lua5.1
  - luajit
