shell_packages_utility:
  - bat
  - curl
  - eza
  - fd-find
  - fortune-mod
  - fzf
  - fzy
  - git-delta
  - jq
  - keychain
  - "{{ ansible_facts['distribution_version'] is version('24.04', '>=') | ternary('lf', False) }}"
  - parallel
  - "{{ ansible_facts['distribution_version'] is version('22.04', '>=') | ternary('plocate', 'mlocate') }}"
  - ripgrep
  - sed
  - tmux
  - tree

shell_packages_zsh:
  - zsh
  - zsh-doc

shell_packages_lua:
  - lua5.1
  - luajit
