software_lua_packages:
  - lua5.1
  - luajit

software_purge_packages:
  - command-not-found
  - snapd

software_utility_packages:
  - bat
  - curl
  - eza
  - fd-find
  - fortune-mod
  - fzf
  - fzy
  - "{{ ansible_facts['distribution_version'] is version('13', '>=') | ternary('git-delta', False) }}"
  - jq
  - keychain
  - kitty-terminfo
  - "{{ ansible_facts['distribution_version'] is version('12', '>=') | ternary('lf', False) }}"
  - parallel
  - plocate
  - ripgrep
  - sed
  - tmux
  - tree

software_desktop_packages:
  - keepassxc
  - firefox
  - speedcrunch
  - vlc
