software_lua_packages:
  - lua51
  - luajit

software_purge_packages:
  - "*-bash-completion"
  - "plasma5-pk-updates"

software_utility_packages:
  - bat
  - curl
  - eza
  - fd
  - fortune
  - fzf
  - fzy
  - gh
  - git-delta
  - gnu_parallel
  - jq
  - keychain
  - kitty-terminfo
  - lf
  - plocate
  - ripgrep
  - sed
  - tmux
  - tree

software_desktop_packages:
  - keepassxc
  - firefox
  - speedcrunch
  - vlc
