software_lua_packages:
  - lua5.1
  - luajit

software_purge_packages:
  - command-not-found
  - snapd

software_utility_packages:
  - bat
  - curl
  - eza
  - fd-find
  - fortune-mod
  - fzf
  - fzy
  - git-delta
  - jq
  - keychain
  - kitty-terminfo
  - "{{ ansible_distribution_version is version('24.04', '>=') | ternary('lf', False) }}"
  - parallel
  - "{{ ansible_distribution_version is version('22.04', '>=') | ternary('plocate', 'mlocate') }}"
  - ripgrep
  - sed
  - tmux
  - tree

software_desktop_packages:
  - keepassxc
  - firefox
  - speedcrunch
  - vlc
