tokyonight:
  repo: https://github.com/folke/tokyonight.nvim
  root: "{{ (opt_dir, 'tokyonight-extras') | path_join }}"
  extras: "{{ (tokyonight.root, 'extras') | path_join }}"
  style: tokyonight_storm
